<script>
	export default {
		onLaunch: function() {
			console.log('App Launch')
		},
		onShow: function() {
			console.log('App Show')
		},
		onHide: function() {
			console.log('App Hide')
		}
	}
</script>

<style>
	@import url("/common/css/normalize.css");
	@import url("/common/css/magic.min.css");

	/*每个页面公共css */

	.header {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		padding-top: 15vh;
		padding-bottom: 7vh;
		width: 100vw;
	}

	.footer {
		display: flex;
		justify-content: flex-end;
		position: fixed;
		z-index: 1;
		bottom: 50upx;
		right: 40upx;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-13 17:13:19
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation focus-in-expand-fwd
	 * ----------------------------------------
	 */
	@keyframes focus-in-expand-fwd {
		0% {
			letter-spacing: -0.5em;
			-webkit-transform: translateZ(-800px);
			transform: translateZ(-800px);
			-webkit-filter: blur(12px);
			filter: blur(12px);
			opacity: 0;
		}

		100% {
			-webkit-transform: translateZ(0);
			transform: translateZ(0);
			-webkit-filter: blur(0);
			filter: blur(0);
			opacity: 1;
		}
	}

	.focus-in-expand-fwd {
		animation: focus-in-expand-fwd 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-13 17:26:29
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation scale-in-top
	 * ----------------------------------------
	 */
	@keyframes scale-in-top {
		0% {
			transform: scale(0);
			transform-origin: 50% 0%;
			opacity: 1;
		}

		100% {
			transform: scale(1);
			transform-origin: 50% 0%;
			opacity: 1;
		}
	}

	.scale-in-top {
		animation: scale-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	}

	.animation-delay {
		animation-delay: .3s;
	}

	/* 文字输入效果 */

	.text-input {
		font: bold 200%;
		border-right: 0.1em solid;
		/* width: 16.5em; */
		width: 55vw;
		white-space: nowrap;
		overflow: hidden;
		animation: typing 3s steps(26, end),
			cursor-blink 0.3s step-end infinite alternate;
	}

	@keyframes typing {
		from {
			width: 0;
		}
	}

	@keyframes cursor-blink {
		50% {
			border-color: transparent;
		}
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-13 21:43:34
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation swirl-in-fwd
	 * ----------------------------------------
	 */
	@keyframes swirl-in-fwd {
		0% {
			transform: rotate(-540deg) scale(0);
			opacity: 0;
		}

		100% {
			transform: rotate(0) scale(1);
			opacity: 1;
		}
	}

	.swirl-in-fwd {
		animation: swirl-in-fwd 0.6s ease-out both;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-13 21:47:40
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation bounce-in-top
	 * ----------------------------------------
	 */
	@keyframes bounce-in-top {
		0% {
			transform: translateY(-500px);
			animation-timing-function: ease-in;
			opacity: 0;
		}

		38% {
			transform: translateY(0);
			animation-timing-function: ease-out;
			opacity: 1;
		}

		55% {
			transform: translateY(-65px);
			animation-timing-function: ease-in;
		}

		72% {
			transform: translateY(0);
			animation-timing-function: ease-out;
		}

		81% {
			transform: translateY(-28px);
			animation-timing-function: ease-in;
		}

		90% {
			transform: translateY(0);
			animation-timing-function: ease-out;
		}

		95% {
			transform: translateY(-8px);
			animation-timing-function: ease-in;
		}

		100% {
			transform: translateY(0);
			animation-timing-function: ease-out;
		}
	}

	.bounce-in-top {
		animation: bounce-in-top 1.1s both;
	}

	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-13 23:9:48
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */

	/**
	 * ----------------------------------------
	 * animation slide-in-top
	 * ----------------------------------------
	 */
	@keyframes slide-in-top {
		0% {
			transform: translateY(-1000px);
			opacity: 0;
		}

		100% {
			transform: translateY(0);
			opacity: 1;
		}
	}

	.slide-in-top {
		animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	}

	/* 自由落体遮罩动画 */

	@keyframes free-fall {
		0% {
			position: absolute;
			background-color: #FFFFFF;
			width: 41vw;
			height: 33vh;
			right: 0;
		}

		100% {
			position: absolute;
			background-color: #FFFFFF;
			width: 41vw;
			height: 33vh;
			right: 0;
			transform: translateY(100%);
		}
	}

	.free-fall {
		animation: free-fall 3s ease 1s normal both;
	}
	
	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-14 19:51:48
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation slide-in-blurred-top
	 * ----------------------------------------
	 */
	@keyframes slide-in-blurred-top {
	  0% {
	    transform: translateY(-1000px) scaleY(2.5) scaleX(0.2);
	    transform-origin: 50% 0%;
	    filter: blur(40px);
	    opacity: 0;
	  }
	  100% {
	    transform: translateY(0) scaleY(1) scaleX(1);
	    transform-origin: 50% 50%;
	    filter: blur(0);
	    opacity: 1;
	  }
	}

	.slide-in-blurred-top {
		animation: slide-in-blurred-top 0.5s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
	}
	
	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-14 19:52:52
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation slide-in-blurred-bottom
	 * ----------------------------------------
	 */
	@keyframes slide-in-blurred-bottom {
	  0% {
	    transform: translateY(1000px) scaleY(2.5) scaleX(0.2);
	    transform-origin: 50% 100%;
	    filter: blur(40px);
	    opacity: 0;
	  }
	  100% {
	    transform: translateY(0) scaleY(1) scaleX(1);
	    transform-origin: 50% 50%;
	    filter: blur(0);
	    opacity: 1;
	  }
	}

	.slide-in-blurred-bottom {
		animation: slide-in-blurred-bottom 0.5s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;
	}
	
	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-14 19:54:10
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation fade-in
	 * ----------------------------------------
	 */
	@keyframes fade-in {
	  0% {
	    opacity: 0;
	  }
	  100% {
	    opacity: 1;
	  }
	}

	.fade-in {
		animation: fade-in 1.2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	}
	
	/* ----------------------------------------------
	 * Generated by Animista on 2021-1-16 19:1:27
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation heartbeat
	 * ----------------------------------------
	 */
	@keyframes heartbeat {
	  from {
	    transform: scale(1);
	    transform-origin: center center;
	    animation-timing-function: ease-out;
	  }
	  10% {
	    transform: scale(0.91);
	    animation-timing-function: ease-in;
	  }
	  17% {
	    transform: scale(0.98);
	    animation-timing-function: ease-out;
	  }
	  33% {
	    transform: scale(0.87);
	    animation-timing-function: ease-in;
	  }
	  45% {
	    transform: scale(1);
	    animation-timing-function: ease-out;
	  }
	}

	.heartbeat {
		animation: heartbeat 1.5s ease-in-out infinite both;
	}
</style>
